# Generated by Django 4.2.7 on 2023-12-23 17:00

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(upload_to='Image_blog', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), home.models.validate_file_mime_type]),
        ),
    ]
